name: Testes

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: Rodar testes Jest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Instalar dependências
        run: npm install --legacy-peer-deps

      - name: Instalar Jest globalmente
        run: npm install -g jest

      - name: Rodar testes
        run: npm test
